spring.application.name=BibliotecaU

spring.datasource.url=jdbc:postgresql://localhost:5432/BibliotecaU
spring.datasource.username=postgres
spring.datasource.password=TU_CONTRASEÑA

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true